version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # Use buildkit for faster builds
      args:
        BUILDKIT_INLINE_CACHE: 1
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    # Add healthcheck
  #    healthcheck:
  #      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/api/v1/health"]
  #      interval: 30s
  #      timeout: 10s
  #      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    env_file:
      - .env
#    depends_on:
#      backend:
#        condition: service_healthy