// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PackingRecord struct {
	ID           int32              `json:"id"`
	Datetime     pgtype.Timestamp   `json:"datetime"`
	Pic          string             `json:"pic"`
	GrossWeight  pgtype.Numeric     `json:"gross_weight"`
	PackAQty     int32              `json:"pack_a_qty"`
	PackBQty     int32              `json:"pack_b_qty"`
	PackCQty     int32              `json:"pack_c_qty"`
	RejectWeight pgtype.Numeric     `json:"reject_weight"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
