// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	GetPackingRecords(ctx context.Context, arg GetPackingRecordsParams) ([]PackingRecord, error)
	NewPackingRecord(ctx context.Context, arg NewPackingRecordParams) (PackingRecord, error)
}

var _ Querier = (*Queries)(nil)
